# Generated by Django 3.2 on 2021-04-26 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='profile', to='auth.user', verbose_name='用户')),
                ('openid', models.CharField(max_length=32, verbose_name='OpenId')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_userprofile_related', related_query_name='erp_userprofiles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='图片')),
                ('name', models.CharField(max_length=125, verbose_name='物品名称')),
                ('location', models.CharField(max_length=32, verbose_name='位置')),
                ('mfg', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='有效天数')),
                ('exp', models.DateField(blank=True, null=True, verbose_name='有效日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_goods_related', related_query_name='erp_goodss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ('id',),
            },
        ),
    ]
