# Generated by Django 3.2 on 2021-04-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('mfg', models.DateField(null=True, verbose_name='生产日期')),
                ('vali_days', models.IntegerField(null=True, verbose_name='有效天数')),
                ('exp', models.DateField(null=True, verbose_name='有效日期')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_validate_related', related_query_name='erp_validates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'expire date',
                'ordering': ['exp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='profile', to='auth.user', verbose_name='用户')),
                ('openid', models.CharField(max_length=32, verbose_name='OpenId')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_userprofile_related', related_query_name='erp_userprofiles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'user profile',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('location', models.CharField(max_length=32, verbose_name='位置')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_storagelocation_related', related_query_name='erp_storagelocations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.storagelocation', verbose_name='归属位置')),
            ],
            options={
                'verbose_name': 'storage location',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=0, verbose_name='乐观锁')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('img', models.CharField(max_length=125, verbose_name='图片')),
                ('name', models.CharField(max_length=125, verbose_name='物品名称')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_goods_related', related_query_name='erp_goodss', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.storagelocation', verbose_name='位置')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.userprofile', verbose_name='用户')),
                ('validate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.validate', verbose_name='有效期')),
            ],
            options={
                'verbose_name': 'goods',
                'ordering': ('id',),
            },
        ),
    ]
