# Generated by Django 3.2 on 2021-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ('id',), 'verbose_name': 'goods', 'verbose_name_plural': 'goods'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='图片'),
        ),
    ]
