# Generated by Django 3.2 on 2021-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='created_by',
            field=models.CharField(blank=True, help_text='创建人', max_length=256, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.CharField(blank=True, help_text='创建人', max_length=256, verbose_name='创建人'),
        ),
    ]
