# Generated by Django 3.2 on 2021-04-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20210425_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.storagelocation', verbose_name='归属位置'),
        ),
    ]
