# Generated by Django 3.2 on 2021-04-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_validate_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagelocation',
            name='parent_loc_id',
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.storagelocation', verbose_name='上级行政区划'),
        ),
    ]
