# Generated by Django 3.2 on 2021-04-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210416_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.storagelocation', verbose_name='归属位置'),
        ),
    ]
